apps/products/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
  url(r'^$', views.index, name="index"),
  url(r'^new/$', views.new, name="new"),
  url(r'^create/$', views.create, name="create"),
  url(r'^find/$', views.find, name="find"),
  url(r'^(?P<product_id>\d+)/add_to_cart/$', views.add_to_cart, name="add_to_cart"),
  url(r'^(?P<product_id>\d+)/remove_from_cart/$', views.remove_from_cart, name="remove_from_cart"),
  url(r'^(?P<product_id>\d+)/show/$', views.show, name="show"),

]

sept_django/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('apps.users.urls', namespace='users')),
    url(r'^', include('apps.products.urls', namespace="products"))
]

apps/products/models.py
from __future__ import unicode_literals

from django.db import models
from ..users.models import User

# Create your models here.
class ProductManager(models.Manager):
  def validate_and_create_product(self, form, user_id):
    errors = []

    if len(form['name']) < 3:
      errors.append('Name must be at least 3 characters long')
    if len(form['description']) < 3:
      errors.append('Description must be at least 3 characters long')
    try:
      price = float(form['price'])
      if price < 0:
        errors.append('Price must be at least $0')
    except:
      errors.append('Price must be a valid number')

    if len(errors) > 0:
      return (False, errors)
    else:
      user = User.objects.get(id=user_id)
      product = self.create(name=form['name'], price=price, description=form['description'], creator=user)
      return (True, product)

  def add_to_cart(self, product_id, user_id):
    try:
      product = self.get(id=product_id)
      user = User.objects.get(id=user_id)
      product.users.add(user)
      product.save()
    except:
      print 'SOMETHING WENT TERRIBLY WRONG'

  def remove_from_cart(self, product_id, user_id):
    try:
      product = self.get(id=product_id)
      user = User.objects.get(id=user_id)
      product.users.remove(user)
      product.save()
    except:
      print 'SOMETHING WENT TERRIBLY WRONG'

class Product(models.Model):
  name = models.CharField(max_length=255)
  price = models.FloatField()
  description = models.TextField()
  creator = models.ForeignKey(User, related_name="created_products")
  users = models.ManyToManyField(User, related_name="products")
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  objects = ProductManager()

  def __str__(self):
    return self.name

apps/products/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponse
from .models import Product
from django.core import serializers
import json

# Create your views here.
def index(req):
  if 'user_id' not in req.session:
    return redirect('users:new')
  context = {
    'available_products': Product.objects.exclude(users=req.session['user_id']),
    'cart_products': Product.objects.filter(users=req.session['user_id'])
  }
  return render(req, 'products/index.html', context)

def new(req):
  if 'user_id' not in req.session:
    return redirect('users:new')
  return render(req, 'products/new.html')

def create(req):
  valid, response = Product.objects.validate_and_create_product(req.POST, req.session['user_id'])
  if not valid:
    for error in response:
      messages.error(req, error)
    return redirect('products:new')
  else:
    return redirect('products:index')

def add_to_cart(req, product_id):
  Product.objects.add_to_cart(product_id, req.session['user_id'])
  return redirect('products:index')

def remove_from_cart(req, product_id):
  Product.objects.remove_from_cart(product_id, req.session['user_id'])
  return redirect('products:index')

def find(req):
  return render(req, 'products/find.html')

def show(req, product_id):
  product = Product.objects.filter(id=product_id)
  if len(product) == 0:
    error = {
      'content': 'Product not found'
    }
    return HttpResponse(json.dumps(error), content_type="application/json", status=404)
  
  product = serializers.serialize('json', product)
  return HttpResponse(product, content_type="application/json", status=200)

apps/products/templates/products/find.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" type="text/css" 
   href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
  <link rel="stylesheet" type="text/css" 
   href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css">
  <script 
   src="https://code.jquery.com/jquery-3.2.1.min.js" 
   integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" 
   crossorigin="anonymous"></script>
  {% load static %}
  <script src="{% static 'products/js/script.js' %}"></script>
  <title>Document</title>
</head>
<body>
  <div class="container">
    <h1>Showing Product</h1>
    <h2>Search product by id</h2>
    <input type="number" id="product-id">
    <a href="#" class="button" id="search-product">Search</a>
    <div id="product">
    </div>
  </div>
</body>
</html>

apps/products/templates/products/index.html
{% extends './layout.html' %}
{% block body %}
  <h1>Products</h1>
  <h2>Your Cart:</h2>
  <ul>
    {% for product in cart_products %}
      <li>{{ product.name }} - ${{ product.price }}, <a href="{% url 'products:remove_from_cart' product.id %}" class="button">Remove From Cart</a></li>
    {% endfor %}
  </ul>
  <h2>Available Products:</h2>
  <ul>
    {% for product in available_products %}
      <li>{{ product.name }} - ${{ product.price }}, <a href="{% url 'products:add_to_cart' product.id %}" class="button">Add to Cart</a></li>
    {% endfor %}
  </ul>
{% endblock %}

apps/products/templates/products/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css">
    {% block head %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <div class="container">
      {% block body %}{% endblock %}
    </div>
  </body>
</html>

apps/products/templates/products/new.html
{% extends './layout.html' %}
{% block body %}
  <h1>Create a New Product</h1>
  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}
  <form action="{% url 'products:create' %}" method="post">
    {% csrf_token %}
    <label for="name">Name:</label>
    <input type="text" name="name" placeholder="Shoelaces">
    <label for="price">Price:</label>
    <input type="number" name="price" placeholder="1.99" step="0.01">
    <label for="description">Description:</label>
    <textarea name="description" id="" cols="30" rows="10"></textarea>
    <input type="submit" value="Create Product">
  </form>
{% endblock %}